import type { Metadata } from "next";
import type { ReactNode } from "react";
import Link from "next/link";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import AuthButtons from "@/components/AuthButtons";
import { AuthProvider } from "@/context/AuthContext";
import { getUserFromCookie } from "@/lib/auth";

export const metadata: Metadata = {
  title: "Cours NextJS",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const user = await getUserFromCookie();
  return (
    <html lang="fr">
      <body className="bg-background text-foreground font-sans shadow">

        <AuthProvider initialUser={user && { id: user.id, username: user.username }}>
          <header className="bg-accent-muted shadow-sm">
            <nav className="container mx-auto px-4 py-5 flex justify-between items-center">
              <div className="flex items-center gap-4">
                <Link href="/" className="flex items-center gap-2">
                  <h1 className="text-2xl font-bold tracking-wide text-white">
                    Projet Étudiant
                  </h1>
                </Link>
                <ul className="flex gap-4 text-sm font-medium text-secondary items-center">

                  <li>
                    <Link href="/a-propos" className="hover:text-accent transition-colors px-2">
                      À propos
                    </Link>
                  </li>
                  <li>
                    <Link href="/contact" className="hover:text-accent transition-colors px-2">
                      Contact
                    </Link>
                  </li>
                </ul>
              </div>

              <AuthButtons />
            </nav>
          </header>
          <main className="container mx-auto px-4 py-12">{children}</main>

          <Toaster position="top-center" />

        </AuthProvider>
      </body>
    </html>
  );
}
