import type { Metadata } from "next";
import type { ReactNode } from "react";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Cours NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="fr">
      <body className="bg-background text-foreground font-sans">
        <header className="bg-accent-muted shadow-sm border-b border-accent">
          <nav className="container mx-auto px-4 py-5 flex justify-between items-center">
            <h1 className="text-2xl font-bold tracking-wide text-accent">
              Projet Étudiant
            </h1>
            <ul className="flex gap-6 text-sm font-medium text-primary">
              <li>
                <Link href="/" className="hover:text-accent transition-colors">
                  Accueil
                </Link>
              </li>
              <li>
                <Link href="/a-propos" className="hover:text-accent transition-colors">
                  À propos
                </Link>
              </li>
              <li>
                <Link href="/contact" className="hover:text-accent transition-colors">
                  Contact
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className="container mx-auto px-4 py-12">{children}</main>
      </body>
    </html>
  );
}
