name: Lint

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]


jobs:
  lint:
    name: Exécuter ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Installer les dépendances
        run: npm ci

      - name: Lancer ESLint
        run: npm run lint
